[project]
name = "dqm-vision-bench"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = ">=3.11"
ipykernel = "*"
numpy = "*"
pandas = "*"
requests = "*"
python-dotenv = "*"
sentence-transformers = "*"
pyyaml = "*"

[pypi-dependencies]
rank-bm25 = "*"
langchain-huggingface = "*"
